const EVENTS = {
  STATE_GET: 'STATE_GET',
  STATE_UPDATED: 'STATE_UPDATED',

  PLAYLIST_ADD: 'PLAYLIST_ADD',
  PLAYLIST_ADDED: 'PLAYLIST_ADDED',

  SERIES_DELETE: 'SERIES_DELETE',
  SERIES_DELETED: 'SERIES_DELETED',

  SERIES_REFRESH: 'SERIES_REFRESH',
  SERIES_REFRESHED: 'SERIES_REFRESHED',

  EPISODE_WATCH: 'EPISODE_WATCH',
  EPISODE_WATCHED: 'EPISODE_WATCHED',

  EPISODE_PROGRESS: 'EPISODE_PROGRESS',
  EPISODE_PROGRESS_SAVED: 'EPISODE_PROGRESS_SAVED',

  SETTINGS_UPDATE: 'SETTINGS_UPDATE',
  SETTINGS_UPDATED: 'SETTINGS_UPDATED',

  LICENSE_VERIFY: 'LICENSE_VERIFY',
  LICENSE_VERIFIED: 'LICENSE_VERIFIED',

  OPEN_SERIES_TAB: 'OPEN_SERIES_TAB',

  AUTO_REFRESH_CHECK: 'AUTO_REFRESH_CHECK',
  NEW_EPISODES_FOUND: 'NEW_EPISODES_FOUND',

  FETCH_CHANNEL_PLAYLISTS: 'FETCH_CHANNEL_PLAYLISTS',

  PLAYLIST_SEARCH: 'PLAYLIST_SEARCH',

  SET_API_KEY: 'SET_API_KEY',
  STORAGE_RESET: 'STORAGE_RESET',
  SERIES_COMPLETE_TOGGLE: 'SERIES_COMPLETE_TOGGLE'
}

export { EVENTS }
