const EVENTS = {
  STATE_GET: 'STATE_GET',
  STATE_UPDATED: 'STATE_UPDATED',

  PLAYLIST_ADD: 'PLAYLIST_ADD',

  SERIES_DELETE: 'SERIES_DELETE',

  SERIES_REFRESH: 'SERIES_REFRESH',

  EPISODE_WATCH: 'EPISODE_WATCH',

  EPISODE_PROGRESS: 'EPISODE_PROGRESS',

  SETTINGS_UPDATE: 'SETTINGS_UPDATE',

  LICENSE_VERIFY: 'LICENSE_VERIFY',

  OPEN_SERIES_TAB: 'OPEN_SERIES_TAB',

  FETCH_CHANNEL_PLAYLISTS: 'FETCH_CHANNEL_PLAYLISTS',

  PLAYLIST_SEARCH: 'PLAYLIST_SEARCH',

  SET_API_KEY: 'SET_API_KEY',
  STORAGE_RESET: 'STORAGE_RESET',
  SERIES_COMPLETE_TOGGLE: 'SERIES_COMPLETE_TOGGLE',
  SET_ICON_THEME: 'SET_ICON_THEME',
  ACTIVATE_LICENSE: 'ACTIVATE_LICENSE'
}

export { EVENTS }
