const EVENTS = {
  STATE_GET: 'STATE_GET',
  STATE_UPDATED: 'STATE_UPDATED',

  PLAYLIST_ADD: 'PLAYLIST_ADD',

  SERIES_DELETE: 'SERIES_DELETE',

  SERIES_REFRESH: 'SERIES_REFRESH',

  EPISODE_WATCH: 'EPISODE_WATCH',
  EPISODE_PROGRESS: 'EPISODE_PROGRESS',
  GET_NEXT_EPISODE: 'GET_NEXT_EPISODE',
  PLAYLIST_EXISTS: 'PLAYLIST_EXISTS',

  SETTINGS_UPDATE: 'SETTINGS_UPDATE',

  LICENSE_VERIFY: 'LICENSE_VERIFY',

  OPEN_SERIES_TAB: 'OPEN_SERIES_TAB',

  FETCH_CHANNEL_PLAYLISTS: 'FETCH_CHANNEL_PLAYLISTS',

  PLAYLIST_SEARCH: 'PLAYLIST_SEARCH',

  STORAGE_RESET: 'STORAGE_RESET',
  SERIES_COMPLETE_TOGGLE: 'SERIES_COMPLETE_TOGGLE',
  SET_ICON_THEME: 'SET_ICON_THEME',
  ACTIVATE_LICENSE: 'ACTIVATE_LICENSE',

  SYNC_LOGIN: 'SYNC_LOGIN',
  SYNC_LOGOUT: 'SYNC_LOGOUT',
  SYNC_STATUS: 'SYNC_STATUS',
  SYNC_NOW: 'SYNC_NOW'
}

export { EVENTS }
